---
fullname: coq-http
shortname: coq-http
opam_name: coq-http
organization: liyishuai
circleci: true
ci_extra_dev: true
synopsis: HTTP in Coq
description: HTTP specification in Coq, testable and verifiable
authors:
  - name: Yishuai Li
    email: yishuai@cis.upenn.edu
  - name: Yao Li
    email: liyao@cis.upenn.edu
  - name: Azzam Althagafi
    email: aazzam@cis.upenn.edu
  - name: Li-yao Xia
    email: xialiyao@cis.upenn.edu
  - name: Benjamin C. Pierce
    email: bcpierce@cis.upenn.edu
license:
  - fullname: GNU Affero General Public License v3.0 or later
    identifier: AGPL-3.0-or-later
dependencies:
  - description: '[ITreeIO](https://github.com/Lysxia/coq-itree-io)'
    opam:
      name: coq-itree-io
  - description: '[Parsec](https://github.com/liyishuai/coq-parsec)'
    opam:
      name: coq-parsec
namespace: HTTP
opam-file-maintainer: 'Yishuai Li <yishuai@cis.upenn.edu>'
supported_coq_versions:
  text: 8.12 or later
  opam: '{ >= "8.12~" }'
tested_coq_opam_versions:
  - version: 'dev'
  - version: '8.12'
