---
fullname: coq-http
shortname: coq-http
opam_name: coq-http
organization: liyishuai
circleci: true
synopsis: HTTP in Coq
description: HTTP specification in Coq, testable and verifiable
authors:
  - name: Yishuai Li
    email: yishuai@cis.upenn.edu
  - name: Li-yao Xia
    email: xialiyao@cis.upenn.edu
  - name: Yao Li
    email: liyao@cis.upenn.edu
  - name: Azzam Althagafi
    email: aazzam@cis.upenn.edu
  - name: Benjamin C. Pierce
    email: bcpierce@cis.upenn.edu
license:
  - fullname: Mozilla Public License 2.0
    identifier: MPL-2.0
dependencies:
  - description: '[OCamlbuild](https://github.com/ocaml/ocamlbuild)'
    opam:
      name: ocamlbuild
      version: '{ >= "0.14.1" }'
  - description: '[ITreeIO](https://github.com/Lysxia/coq-itree-io)'
    opam:
      name: coq-itree-io
      version: '{ >= "0.1.0" }'
  - description: '[Parsec](https://github.com/liyishuai/coq-parsec)'
    opam:
      name: coq-parsec
      version: '{ >= "0.1.1" }'
  - description: '[QuickChick](https://github.com/QuickChick/QuickChick/)'
    opam:
      name: coq-quickchick
      version: '{ >= "1.6.3" }'
  - description: '[JSON](https://github.com/liyishuai/coq-json)'
    opam:
      name: coq-json
      version: '{ >= "0.1.1" }'
test_target: test
install_flag: INSTALLDIR=%{bin}%
categories:
  - name: >-
      Computer Science/Concurrent Systems and Protocols/Correctness of specific
      protocols
  - name: Miscellaneous/Extracted Programs/Decision procedures
keywords:
  - name: co-induction
  - name: extraction
  - name: reactive systems
date: 2022-05-31
namespace: HTTP
opam-file-maintainer: 'Yishuai Li <yishuai@cis.upenn.edu>'
supported_coq_versions:
  text: 8.13 or later
  opam: '{ >= "8.13~" }'
tested_coq_opam_versions:
  - version: '8.13-ocaml-4.12-flambda'
  - version: '8.14-ocaml-4.12-flambda'
  - version: '8.15-ocaml-4.12-flambda'
  - version: 'dev-ocaml-4.12-flambda'
publications:
  - pub_title: >-
      From C to Interaction Trees:
      Specifying, Verifying, and Testing a Networked Server
    pub_url: https://doi.org/10.1145/3293880.3294106
    pub_doi: 10.1145/3293880.3294106
  - pub_title: Model-Based Testing of Networked Applications
    pub_url: https://doi.org/10.1145/3460319.3464798
    pub_doi: 10.1145/3460319.3464798
  - pub_title: Verifying an HTTP Key-Value Server with Interaction Trees and VST
    pub_url: https://drops.dagstuhl.de/opus/volltexte/2021/13927
    pub_doi: 10.4230/LIPIcs.ITP.2021.32
